apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-api-deployment
  namespace: boldbi-cloud-test
spec:
  selector:
    matchLabels:
      app: bi-api
  # replicas: 1
  template:
    metadata:
      labels:
        app: bi-api
    spec:
      containers:
      - name: bi-api-container
        image: us-docker.pkg.dev/boldbi-dev-296107/boldbik8s/boldbi-server-api-cloud:5.4.44202205301738407631
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750M
          limits:
            cpu: 250m
            memory: 750M
        envFrom:
        - secretRef:
              name: boldbi-web-secret
        - secretRef:
              name: published-cdn-link
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
