apiVersion: v1
kind: Service
metadata:
  name: bi-jobs-service
  namespace: boldbi-cloud-test
  annotations:
    cloud.google.com/backend-config: '{"default": "development-backend"}'
  labels:
    app: bi-jobs
spec:
  type: NodePort
  ports:
  - name: bi-jobs-port
    port: 6006
    targetPort: 80
    protocol: TCP
  selector:
    app: bi-jobs
