apiVersion: v1
kind: Service
metadata:
  name: bi-api-service
  namespace: boldbi-cloud-test
  labels:
    app: bi-api
spec:
  type: NodePort
  ports:
  - name: bi-api-port
    port: 6005
    targetPort: 80
    protocol: TCP
  selector:
    app: bi-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-api-deployment
  namespace: boldbi-cloud-test
spec:
  selector:
    matchLabels:
      app: bi-api
  replicas: 1
  template:
    metadata:
      labels:
        app: bi-api
    spec:
      containers:
      - name: bi-api-container
        image: gcr.io/boldbi-dev-296107/boldbi-server-api-cloud:4.2.69_latest2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bi-api-hpa
  namespace: boldbi-cloud-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bi-api-deployment
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 10
        periodSeconds: 60