bases:
  - ../manifests
secretGenerator:
  - name: published-cdn-link
    namespace: boldbi-cloud-test
    literals:
    - AppSettings_EndPoints_CdnLink=https://cdn.boldbi.com/ds/202202011227460316
    - AppSettings_EndPoints_DesignerCdnLink=http://cdn.boldbi.com/ds/202202011227460316
