apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boldbi-cloud-test

resources:
  - ../manifests

secretGenerator:
  - name: published-cdn-link
    literals:
    - AppSettings_EndPoints_CdnLink=https://cdn.boldbi.com/ds/202202011227460316
    - AppSettings_EndPoints_DesignerCdnLink=https://cdn.boldbi.com/ds/202202011227460316
