apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boldbi-cloud-test

resources:
  - ../manifests

secretGenerator:
  - name: published-cdn-link
    literals:
    - AppSettings_EndPoints_CdnLink=https://cdn.boldbi.com/ds/202209161213015668
    - AppSettings_EndPoints_DesignerCdnLink=https://cdn.boldbi.com/ds/202209161213015668

images:
  - name: us-docker.pkg.dev/boldbi-dev-296107/boldbik8s/boldbi-server-web-cloud
    newTag:5.5.5202209201010405765

  - name: us-docker.pkg.dev/boldbi-dev-296107/boldbik8s/boldbi-server-api-cloud
    newTag:5.5.5202209201010405765

  - name: us-docker.pkg.dev/boldbi-dev-296107/boldbik8s/boldbi-server-jobs-cloud
    newTag:5.5.5202209201010405765

  - name: us-docker.pkg.dev/boldbi-dev-296107/boldbik8s/boldbi-designer-cloud
    newTag:5.5.5202209201010405765
