apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boldbi-cloud-test

resources:
  - ../manifests

secretGenerator:
  - name: published-cdn-link
    literals:
    - AppSettings_EndPoints_CdnLink=https://cdn.boldbi.com/ds/202202081543378024
    - AppSettings_EndPoints_DesignerCdnLink=https://cdn.boldbi.com/ds/202202081543378024

images:
  - name: gcr.io/boldbi-dev-296107/boldbi-server-web-cloud
    newTag:4.2.69-Testing-001202202081533155135

  - name: gcr.io/boldbi-dev-296107/boldbi-server-api-cloud
    newTag:4.2.69-Testing-001202202081533155135

  - name: gcr.io/boldbi-dev-296107/boldbi-server-jobs-cloud
    newTag:4.2.69-Testing-001202202081533155135

  - name: gcr.io/boldbi-dev-296107/boldbi-designer-cloud
    newTag:4.2.69-Testing-001202202081533155135
