apiVersion: v1
kind: Service
metadata:
  name: bi-refresh-service-service
  namespace: boldbi-cloud-test  
  labels:
    app: bi-refresh-service
spec:
  type: NodePort
  ports:
  - name: bi-refresh-service-port
    port: 6008
    targetPort: 80
    protocol: TCP
  selector:
    app: bi-refresh-service