apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-refresh-service-deployment
  namespace: boldbi-cloud-test
spec:
  selector:
    matchLabels:
      app: bi-refresh-service
  replicas: 1
  template:
    metadata:
      labels:
        app: bi-refresh-service
    spec:
      containers:
      - name: bi-refresh-service-container
        image: gcr.io/boldbi-dev-296107/boldbi-designer-cloud:4.2.69-202202021831036400
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 3m
            memory: 116M
          limits:
            cpu: 3m
            memory: 116M
        envFrom:
        - secretRef:
              name: boldbi-designer-secret
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10